# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Edit(object):
    def setupUi(self, Edit):
        Edit.setObjectName("Edit")
        Edit.resize(271, 140)
        self.verticalLayout = QtWidgets.QVBoxLayout(Edit)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeEdit = QtWidgets.QTimeEdit(Edit)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout.addWidget(self.timeEdit)
        self.weekCheck = QtWidgets.QHBoxLayout()
        self.weekCheck.setSpacing(1)
        self.weekCheck.setObjectName("weekCheck")
        self.mon = QtWidgets.QCheckBox(Edit)
        self.mon.setObjectName("mon")
        self.weekCheck.addWidget(self.mon)
        self.tue = QtWidgets.QCheckBox(Edit)
        self.tue.setObjectName("tue")
        self.weekCheck.addWidget(self.tue)
        self.wed = QtWidgets.QCheckBox(Edit)
        self.wed.setObjectName("wed")
        self.weekCheck.addWidget(self.wed)
        self.thu = QtWidgets.QCheckBox(Edit)
        self.thu.setObjectName("thu")
        self.weekCheck.addWidget(self.thu)
        self.fri = QtWidgets.QCheckBox(Edit)
        self.fri.setObjectName("fri")
        self.weekCheck.addWidget(self.fri)
        self.sat = QtWidgets.QCheckBox(Edit)
        self.sat.setObjectName("sat")
        self.weekCheck.addWidget(self.sat)
        self.sun = QtWidgets.QCheckBox(Edit)
        self.sun.setObjectName("sun")
        self.weekCheck.addWidget(self.sun)
        self.verticalLayout.addLayout(self.weekCheck)
        self.saveButton = QtWidgets.QPushButton(Edit)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(Edit)
        QtCore.QMetaObject.connectSlotsByName(Edit)

    def retranslateUi(self, Edit):
        _translate = QtCore.QCoreApplication.translate
        Edit.setWindowTitle(_translate("Edit", "設定鬧鐘"))
        self.timeEdit.setDisplayFormat(_translate("Edit", "HH:mm"))
        self.mon.setText(_translate("Edit", "一"))
        self.tue.setText(_translate("Edit", "二"))
        self.wed.setText(_translate("Edit", "三"))
        self.thu.setText(_translate("Edit", "四"))
        self.fri.setText(_translate("Edit", "五"))
        self.sat.setText(_translate("Edit", "六"))
        self.sun.setText(_translate("Edit", "日"))
        self.saveButton.setText(_translate("Edit", "儲存"))
