# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(300, 300)
        self.gridLayout = QtWidgets.QGridLayout(Main)
        self.gridLayout.setObjectName("gridLayout")
        self.alarmList = QtWidgets.QListWidget(Main)
        self.alarmList.setEnabled(True)
        self.alarmList.setObjectName("alarmList")
        self.gridLayout.addWidget(self.alarmList, 0, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(Main)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 2, 0, 1, 1)
        self.Detected = QtWidgets.QHBoxLayout()
        self.Detected.setObjectName("Detected")
        self.startButton = QtWidgets.QPushButton(Main)
        self.startButton.setObjectName("startButton")
        self.Detected.addWidget(self.startButton)
        self.statusButton = QtWidgets.QPushButton(Main)
        self.statusButton.setObjectName("statusButton")
        self.Detected.addWidget(self.statusButton)
        self.stopButton = QtWidgets.QPushButton(Main)
        self.stopButton.setObjectName("stopButton")
        self.Detected.addWidget(self.stopButton)
        self.gridLayout.addLayout(self.Detected, 1, 0, 1, 1)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "翰寶王柏盛十分-隨機手勢鬧鐘"))
        self.addButton.setText(_translate("Main", "新增鬧鐘"))
        self.startButton.setText(_translate("Main", "開始偵測"))
        self.statusButton.setText(_translate("Main", "狀態"))
        self.stopButton.setText(_translate("Main", "停止偵測"))
