# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(260, 300)
        self.addButton = QtWidgets.QPushButton(Main)
        self.addButton.setGeometry(QtCore.QRect(220, 85, 20, 20))
        self.addButton.setObjectName("addButton")
        self.alarmList = QtWidgets.QListWidget(Main)
        self.alarmList.setEnabled(True)
        self.alarmList.setGeometry(QtCore.QRect(20, 110, 221, 171))
        self.alarmList.setObjectName("alarmList")
        self.status = QtWidgets.QLabel(Main)
        self.status.setGeometry(QtCore.QRect(20, 85, 20, 20))
        self.status.setText("")
        self.status.setObjectName("status")
        self.currentTime = QtWidgets.QLCDNumber(Main)
        self.currentTime.setGeometry(QtCore.QRect(20, 10, 220, 80))
        self.currentTime.setLineWidth(0)
        self.currentTime.setDigitCount(8)
        self.currentTime.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.currentTime.setObjectName("currentTime")

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "翰寶王柏盛十分-隨機手勢鬧鐘"))
        self.addButton.setText(_translate("Main", "＋"))
